# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = uno
ARDUINO_LIBS = Wire
ARDUINO_LIBS += apds-9130-driver 

USER_LIB_PATH += ../

include $(ARDMK_DIR)/Arduino.mk


